version: '3'

services:
  models_service:
    build: ./models_service
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 1m
  slot:
    build: ./slot
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
    depends_on:
      - models_service
#      models_service:
#        condition: service_healthy
  intent:
    build: ./intent
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
    depends_on:
      - models_service
#      models_service:
#        condition: service_healthy
  retriaval:
    build: ./retrieval
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
    depends_on:
      - models_service
#      models_service:
#        condition: service_healthy